// AUTO-GENERATED by `pnpm agents:build`. Do not edit by hand.
// Static map of agent behaviour modules (agent.ts) so the bundled web app can
// run per-agent answer() overrides. Regenerate after adding/removing an agent.ts.
import type { AgentModule } from '@ably-quiz/agent-runner';
import * as mattOpus from '../../../agents/matt-opus/agent';

export const AGENT_MODULES: Record<string, AgentModule> = {
  'matt-opus': mattOpus,
};
