// `pnpm agents:build` (§S6.4). Generates the static agent-module index the
// bundled web app imports, so a contributor's agent.ts `answer()` override runs
// in the on-demand /api/agent-turn route. The CLIs load agent.ts dynamically
// (tsx); Next can't, so it needs these STATIC imports — hence codegen. Run after
// adding/removing an agent.ts (wired into web dev/build). The output is committed.

import { readdir, stat, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const REPO_ROOT = new URL('../../../', import.meta.url);
const AGENTS_DIR = fileURLToPath(new URL('agents/', REPO_ROOT));
const OUT = fileURLToPath(new URL('apps/web/lib/agent-modules.generated.ts', REPO_ROOT));

/** matt-opus → mattOpus (a safe JS identifier for the import binding). */
function ident(slug: string): string {
  return slug.replace(/[^a-zA-Z0-9]+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase());
}

async function hasAgentTs(dir: string): Promise<boolean> {
  try {
    await stat(join(dir, 'agent.ts'));
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  let names: string[];
  try {
    names = (await readdir(AGENTS_DIR)).sort();
  } catch (err) {
    console.error(`cannot read agents dir: ${err instanceof Error ? err.message : err}`);
    process.exit(1);
  }

  const slugs: string[] = [];
  for (const name of names) {
    if (await hasAgentTs(join(AGENTS_DIR, name))) slugs.push(name);
  }

  const header = [
    '// AUTO-GENERATED by `pnpm agents:build`. Do not edit by hand.',
    '// Static map of agent behaviour modules (agent.ts) so the bundled web app can',
    '// run per-agent answer() overrides. Regenerate after adding/removing an agent.ts.',
    "import type { AgentModule } from '@ably-quiz/agent-runner';",
  ];
  const imports = slugs.map((s) => `import * as ${ident(s)} from '../../../agents/${s}/agent';`);
  const entries = slugs.map((s) => `  '${s}': ${ident(s)},`);
  const body = [
    '',
    'export const AGENT_MODULES: Record<string, AgentModule> = {',
    ...entries,
    '};',
    '',
  ];
  const file = [...header, ...imports, ...body].join('\n');

  await writeFile(OUT, file, 'utf8');
  console.log(`agents:build — wrote ${slugs.length} module(s) to agent-modules.generated.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
